apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: trippy-planner

resources:
- ../../base

images:
- name: ghcr.io/homelab1025/trippy-planner-frontend
  newName: ghcr.io/homelab1025/trippy-planner-frontend
  newTag: latest
- name: ghcr.io/homelab1025/trippy-planner-backend
  newName: ghcr.io/homelab1025/trippy-planner-backend
  newTag: latest
