apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: trippy-planner

resources:
- ../../base

images:
- name: trippy-planner
  newName: ghcr.io/homelab1025/trippy-planner
  newTag: latest
