spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.flyway.enabled=true

server.servlet.context-path=/api

app.base-url=${APP_BASE_URL}
app.session-expiry-minutes=${SESSION_EXPIRY_MINUTES:43200}

resend.api-key=${RESEND_API_KEY}
