name: Coverage

on:
  push:
    branches: ["master"]

permissions:
  contents: read

jobs:
  generate:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Generate coverage report
        run: make coverage-frontend

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: frontend/coverage

  deploy:
    runs-on: ubuntu-latest
    needs: generate
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
